### ISSUE TITLE
Quadric Initialization for Incremental solvers

### ISSUE THREAD

**Issue by p-akanksha** [best-of-acrv/quadricslam#2]
Hi, 

I've been trying to use QuadricSLAM with one of my academic projects. I've been looking for the part of code that does quadric initialization for incremental solvers but I've been unable to locate it. It'll be really helpful if you can point me in the right direction. 

-Akanksha

P.S. Thanks for the amazing work.

**Comment by lachlan-nicholson** [comment]
The quadric initialisation currently resides in examples/python/example_frontend/system.py. We have made a few changes that will move this into a more obvious place and these will be pushed soon.

**Comment by p-akanksha** [comment]
Thanks for the update.
