### ISSUE TITLE
Unknown CMake command "wrap_and_install_library_cython".

### ISSUE THREAD

**Issue by Hao-HUST** [best-of-acrv/quadricslam#4]
Hi, thanks for sharing.

When I try to cmake the project with "QSLAM_BUILD_PYTHON_WRAP = ON", the errors occurred:

> hao@hao-2288H-V5:/mnt/sdb1/hao/project/quadricslam/build$ cmake ..
-- GTSAM include directory:  /usr/local/lib/cmake/GTSAM/../../../include
CMake Error at CMakeLists.txt:38 (include):
  include could not find load file:
    GtsamCythonWrap
-- Wrote /mnt/sdb1/hao/project/quadricslam/build/QUADRICSLAMConfig.cmake
-- GTSAM include directory:  /usr/local/lib/cmake/GTSAM/../../../include
CMake Error at CMakeLists.txt:128 (wrap_and_install_library_cython):
  Unknown CMake command "wrap_and_install_library_cython".
-- Configuring incomplete, errors occurred!
See also "/mnt/sdb1/hao/project/quadricslam/build/CMakeFiles/CMakeOutput.log".
See also "/mnt/sdb1/hao/project/quadricslam/build/CMakeFiles/CMakeError.log".

Any suggestions about it?

**Comment by lachlan-nicholson** [comment]
What version of GTSAM are you using? This repository was originally tested with GTSAM 4.0.2, though this has become quite outdated. We are now in the process of upgrading to be compatible with GTSAM 4.1.

**Comment by Hao-HUST** [comment]
My original GTSAM is cloned from the develop branch, and according to your suggestion, I use GTSAM 4.0.2  to try again, it works.

Thanks!
